- hosts: services

  tasks:

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: true

    - name: create root directory
      file:
        path: "{{root_dir}}"
        state: directory

    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: true

    - name: upload index file
      ansible.builtin.template:
        src: files/index.html.j2
        dest: "{{root_dir}}/index.html"
      become: true

  handlers:

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true
