---
- name: Update packages
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: Enable passwordless sudo for "{{ username }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
