---
- name: Ensure all necessary groups are created
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
    - docker
    - samba
    - "{{ username }}"

- name: Ensure the non-root user is created
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ user_password }}"
    groups:
      - sudo
      - docker
      - users
    append: true
    shell: "{{ shell }}"
    update_password: on_create

- name: Suppress login message (hushlogin)
  ansible.builtin.file:
    path: "/home/{{ username }}/.hushlogin"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch
